# Generated by Django 4.0.4 on 2022-07-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pollapp', '0002_option_votes_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_question',
            field=models.CharField(default='Question?', max_length=64),
            preserve_default=False,
        ),
    ]
