# Generated by Django 4.0.4 on 2022-08-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pollapp', '0004_alter_poll_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='url',
            field=models.CharField(default='def', max_length=24),
            preserve_default=False,
        ),
    ]
