# Generated by Django 4.0.4 on 2022-08-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pollapp', '0006_poll_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
